<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>LongYinEnglish</AssemblyName>
    <RootNamespace>LongYinEnglish</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader"><HintPath>..\Refs\MelonLoader.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>..\Refs\0Harmony.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
